package courageous.models;

import java.util.Date;
import java.util.UUID;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGenerateStrategy;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedTimestamp;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Assignations")
public class Assignation {
    private UUID inventoryItemId;
    private UUID secret;
    private String userName;
    private String userPhone;
    private boolean checkedOut;
    private Date timestamp;

    @DynamoDBHashKey(attributeName = "InventoryItemId")
    public UUID getInventoryItemId() {
        return this.inventoryItemId;
    }

    public void setInventoryItemId(UUID inventoryItemId) {
        this.inventoryItemId = inventoryItemId;
    }

    @DynamoDBIndexHashKey(attributeName = "Secret", globalSecondaryIndexName = "Secret-index")
    @DynamoDBAutoGeneratedKey
    public UUID getSecret() {
        return this.secret;
    }

    public void setSecret(UUID secret) {
        this.secret = secret;
    }

    @DynamoDBAttribute(attributeName = "UserName")
    public String getUserName() {
        return this.userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    @DynamoDBAttribute(attributeName = "UserPhone")
    public String getUserPhone() {
        return this.userPhone;
    }

    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone;
    }

    public boolean isCheckedOut() {
        return this.checkedOut;
    }

    @DynamoDBAttribute(attributeName = "CheckedOut")
    public boolean getCheckedOut() {
        return this.checkedOut;
    }

    public void setCheckedOut(boolean checkedOut) {
        this.checkedOut = checkedOut;
    }

    @DynamoDBAttribute(attributeName = "Timestamp")
    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.ALWAYS)
    public Date getTimestamp() {
        return this.timestamp;
    }

    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }

    // Fluent setters
    public Assignation inventoryItemId(UUID inventoryItemId) {
        this.inventoryItemId = inventoryItemId;
        return this;
    }

    public Assignation secret(UUID secret) {
        this.secret = secret;
        return this;
    }

    public Assignation userName(String userName) {
        this.userName = userName;
        return this;
    }

    public Assignation userPhone(String userPhone) {
        this.userPhone = userPhone;
        return this;
    }

    public Assignation checkedOut(boolean checkedOut) {
        this.checkedOut = checkedOut;
        return this;
    }
}
